### ISSUE TITLE
Deprecate this feedstock?

### ISSUE THREAD

**Issue by bjodah** [conda-forge/pytest-cache-feedstock#3]
from the [original repo](https://bitbucket.org/hpk42/pytest-cache):

    pytest-cache is no longer maintained since its functionality was 
    integrated into pytest core starting with pytest-2.8.0

how does one go about deprecating feedstocks on conda-forge?

**Comment by ocefpaf** [comment]
We can archive it so it does not accept PRs. I'll do that.
